---
name: Update PPA

"on":
  schedule:
    - cron:  '23 4 * * *'
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true
jobs:
  update_ppa:
    runs-on: ubuntu-latest
    permissions:
      contents: write # needs to be able to push to the repo
    env:
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      GPG_KEY_ID: ${{ secrets.GPG_KEY_ID }}
      GPG_KEY_FILE: ${{ secrets.GPG_KEY_FILE }}
    steps:
      - uses: actions/checkout@v4
      - name: Install dependencies
        run: |
          sudo ./install_requirements.sh
      - name: "Import GPG signing key"
        run: |
          echo "${GPG_KEY_FILE}" | base64 -d | gzip -dc | gpg --import
      - name: "Run update"
        run: ./update.sh
      - name: "Run upload"
        run: |
          git config --global user.name 'Github Actions'
          git config --global user.email 'kanidm@users.noreply.github.com'
          git remote set-url origin https://x-access-token:${{ secrets.GITHUB_TOKEN }}@github.com/${{ github.repository }}
          ./upload.sh
